version: "3.9"
services:

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5439:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nats-service-pg
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  nats-streaming:
    image: nats-streaming:0.24.6
    container_name: nats-services
    ports:
     - "4222:4222"

  